### ISSUE TITLE
Write full OSGi bundlepart version

### ISSUE THREAD

**Issue by davenice** [IBM/cics-bundle-maven#15]
At the moment the symbolic name is written into the bundlepart with the version in.

This needs to be updated so that the version is written into the correct xml attribute, separately from the name. So the XML should look something like this:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<osgibundle symbolicname="myosgi" version="1.0.0" jvmserver="JVMONE"/>`

**Comment by ind1go** [comment]
This is an interesting one. The symbolic name and version should come from the OSGi bundle's manifest. I think we should be able to make the assumption that the Maven artifact's artifactId and version are the same as the OSGi bundle's symbolic name and version. Otherwise, we'll fall into the trap that @davenice recently got us out of where we need the full dependency files during the in-IDE validation.

**Comment by davenice** [comment]
@ind1go did you say this could close?

We discussed the issue of the names including versions for other resource (e.g. WAR etc) and decided that it's not a big issue in terms of user impact. In many situations it will be helpful for the version of the bundle to follow it around in naming a bit more.
